services:
  mssql:
    container_name: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"  # Must meet SQL Server password complexity
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  adminer:
    container_name: mssql-adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
